
title: pawsed
author: Pawan Sasanka Ammanamanchi
email: pass2pawan@gmail.com
url : "https://www.pawansasanka.com"
#description: > # this means to ignore newlines until "twitter_username:"
#  I'm an Senior undergrad student researcher working on NLP. I love to
#  read books, articles on various topics. I try to learn what i don't know.

show_excerpts: false # set to true to show excerpts on the homepage
disqus :
  shortname : https-www-pawansasanka-me
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
# site :
# facebook: myfacebook
# twitter: mytwitter
# # google: mygoogle
# # instagram: myinstagram
# # pinterest: mypinterest
# # linkedin: mylinkedin
# # youtube: myyoutube
# # spotify: myspotify
# github: mygithub
# # gitlab: mygitlab
# # lastfm: mylastfm
# # stackoverflow: 7044681/mystackoverflow
# # quora: userquora
# # reddit: username
# medium: medium
# # vimeo: myvimeo
# # lanyrd: mylanyrd
# email: myemail@gmail.com

  social_links:
    twitter: paws_ed
    github:  Shashi456
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - Musings.md
 - Miscellaneous.md
 - deeplearning.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
